import LessonClient from './lesson-client'

const lessons = [
  {slug:'money-follows-value',num:'01.01',title:'Money Follows Value',kicker:'THE FOUNDATION',body:["Money is an exchange for value. People pay when they believe an outcome is worth more to them than what they give up.","AI can increase what one person can produce, but AI does not decide what is valuable. You do.","Start with a customer problem, not a cool feature."],principle:"Ask: “What problem matters enough that someone would pay to solve it?”",examples:["A contractor needs faster estimates → build a quoting workflow.","A creator needs consistent content → build a repeatable content system.","A small company is buried in support questions → organize its knowledge and response workflow."],exercise:"Name three people or businesses you understand. For each, write one thing that wastes time, costs money, frustrates customers, or blocks growth.",challenge:"Choose the most painful problem and talk to one real person connected to it.",check:"What is the stronger starting point? A) A cool AI feature. B) A costly problem a specific customer already has.",answer:"B — the customer problem is the starting point.",milestone:"You can name a customer, a problem, and why solving it matters."},
  {slug:'income-vs-wealth',num:'01.02',title:'Income vs. Wealth',kicker:'THINK LONGER TERM',body:["Income is money coming in. Wealth is what remains and what can continue producing value.","A high income can disappear if spending rises with it. A business can become more valuable through repeat customers, strong margins, systems, brand, and other assets.","Think in layers: earn → keep → reinvest → build assets → improve the engine."],principle:"Do not confuse a bigger paycheck with a stronger financial foundation.",examples:["Reinvest early revenue into better delivery.","Document recurring work so it can eventually be delegated.","Build durable assets alongside revenue."],exercise:"List three ways you currently spend time to earn money. Write one way each could become more repeatable or valuable.",challenge:"Document one recurring task step-by-step so another person could understand it.",check:"Which creates more leverage? A) Repeat the same work forever. B) Improve the process so future work becomes easier or more valuable.",answer:"B — systems can increase the leverage of future effort.",milestone:"You can distinguish cash flow from assets and systems."},
  {slug:'skills-vs-shortcuts',num:'01.03',title:'Skills Beat Shortcuts',kicker:'BUILD CAPABILITY',body:["Shortcuts are fragile when you do not understand the work underneath them.","Use AI to accelerate learning and execution, not to outsource your judgment.","Learn enough sales, research, numbers, product, and operations to make good decisions and know when you need help."],principle:"Every useful skill you build becomes part of your personal operating system.",examples:["Use AI to explain sales, then practice the conversation.","Use AI to draft analysis, then verify important facts.","Use AI to prototype, then put the prototype in front of users."],exercise:"Choose one business skill you want to strengthen and explain why it would make you more valuable.",challenge:"Spend 30 focused minutes learning one fundamental concept, then apply it to a real problem.",check:"What is the danger of blindly trusting AI? A) It may be wrong or incomplete. B) It is always too slow. C) It cannot produce text.",answer:"A — useful output can still be wrong or incomplete.",milestone:"You have chosen one business skill to deliberately strengthen."},
  {slug:'why-people-pay',num:'01.04',title:'Why People Pay',kicker:'UNDERSTAND THE CUSTOMER',body:["People pay for outcomes: convenience, speed, certainty, reduced risk, access, entertainment, status, and more.","The key question is not “Would people like this?” It is “What changes for the customer after they buy?”","Your job is to discover what people already value and build around it."],principle:"Likes are not demand. A meaningful customer outcome is closer to demand.",examples:["Speed: faster turnaround.","Convenience: removing tedious work.","Risk reduction: lowering expensive mistakes."],exercise:"Pick something you recently paid for. Write what you actually bought beyond the physical item.",challenge:"Interview one potential customer about what they do today, what frustrates them, and what success would look like.",check:"Which reveals more? A) “Do you like my idea?” B) “How do you solve this today, and what is frustrating about it?”",answer:"B — existing behavior and frustration provide stronger evidence.",milestone:"You can describe the outcome a customer is actually buying."},
  {slug:'finding-expensive-problems',num:'01.05',title:'Find Expensive Problems',kicker:'FOLLOW THE PAIN',body:["A useful business problem can cost money, time, customers, opportunities, reputation, or peace of mind.","Look for frequency, urgency, consequence, and existing spending. Recurring pain is especially useful.","Do not manufacture pain. Discover it."],principle:"Strong opportunities often hide inside problems people are already paying or struggling to solve.",examples:["Manual data entry repeated every day.","Leads lost because inquiries are answered too slowly.","Marketing content that takes an owner hours every week."],exercise:"List 10 problems you have experienced, observed, or heard businesses discuss.",challenge:"Circle three recurring problems and identify who has them, how they solve them now, and what that solution costs.",check:"Which is stronger evidence? A) People say an idea sounds cool. B) People repeatedly experience pain and spend time or money solving it.",answer:"B — behavior is stronger evidence than compliments.",milestone:"You have three real problems with identifiable customers and alternatives."},
  {slug:'opportunity-vs-hype',num:'01.06',title:'Opportunity vs. Hype',kicker:'LEARN TO FILTER',body:["AI creates real opportunities and enormous noise at the same time.","A real opportunity has a customer, problem, reason to act, reachable market, and plausible delivery model.","You do not need certainty before testing. You need enough evidence to justify the next small test."],principle:"Ask what evidence would make you more confident—and go collect it.",examples:["Trend-first: “Everyone wants agents.” Problem-first: “This business loses leads after hours; can response time improve?”","Hype says scale immediately. Evidence says test with a small group."],exercise:"Take one business idea and write five assumptions that must be true for it to work.",challenge:"Choose the riskiest assumption and design a 48-hour test without spending serious money.",check:"What should happen before a large build? A) Test the riskiest assumption. B) Spend as much as possible.",answer:"A — small tests reduce avoidable risk and improve information.",milestone:"You can turn a vague idea into testable assumptions."},
  {slug:'the-10-problem-challenge',num:'01.07',title:'The 10-Problem Challenge',kicker:'MODULE MILESTONE',body:["You are not leaving with ten business ideas. You are leaving with ten problems worth investigating.","For every problem record: who has it, what happens today, why it matters, what they use now, and what evidence you have.","Choose your top three based on evidence, not excitement. Module 03 will teach validation."],principle:"Entrepreneurs do not need perfect ideas. They need a disciplined process for finding and testing valuable problems.",examples:["Missed after-hours leads → local service company → voicemail/manual follow-up.","Repetitive marketing work → small e-commerce brand → manual creation."],exercise:"Create your 10-problem list and fill in the five evidence fields for every problem.",challenge:"Rank your top three and explain why each deserves validation.",check:"What is the Module 01 deliverable? A) Ten business names. B) Ten real problems plus a researched top three.",answer:"B — we are training your ability to see opportunity before you build.",milestone:"MODULE 01 COMPLETE: You have a problem portfolio and three opportunities ready for validation."}
]

export default function LessonPage({params}:{params:{slug:string}}){
 const lesson=lessons.find(x=>x.slug===params.slug)
 if(!lesson) return <main className="lessonPage"><div className="lessonWrap"><h1>Lesson not found.</h1><a href="/dashboard">Back to dashboard →</a></div></main>
 return <LessonClient lesson={lesson}/>
}
